AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'app/views/spree/api/**/*'
    - 'bin/*'
    - 'cache/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/support/fixture_builder.rb'
    - 'tmp/**/*'
    - 'db/data/*'
    - 'db/data_schema.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'lib/aws-sdk.rb'
    - 'config/initializers/global_constants.rb'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Exclude:
    - 'config/initializers/spree.rb'
    - 'config/initializers/action_mailer.rb'
  Max: 100

Style/Documentation:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: 4

Layout/IndentArray:
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: 4

Style/BlockComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - indented
    - indented_relative_to_receiver
  # By default, the indentation width from Style/IndentationWidth is used
  # But it can be overridden by setting this parameter
  IndentationWidth: 4

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/environments/*.rb'
    - 'config/routes.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Description: Avoid methods longer than 10 lines of code.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#short-methods
  Max: 10

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4
